package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * AlmCenCostos generated by hbm2java
 */
public class AlmCenCostos  implements java.io.Serializable {


     private String codCos;
     private String nomCos;

    public AlmCenCostos() {
    }

    public AlmCenCostos(String codCos, String nomCos) {
       this.codCos = codCos;
       this.nomCos = nomCos;
    }
   
    public String getCodCos() {
        return this.codCos;
    }
    
    public void setCodCos(String codCos) {
        this.codCos = codCos;
    }
    public String getNomCos() {
        return this.nomCos;
    }
    
    public void setNomCos(String nomCos) {
        this.nomCos = nomCos;
    }




}


