package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * AlmFamilias generated by hbm2java
 */
public class AlmFamilias  implements java.io.Serializable {


     private AlmFamiliasId id;
     private String variante;

    public AlmFamilias() {
    }

    public AlmFamilias(AlmFamiliasId id, String variante) {
       this.id = id;
       this.variante = variante;
    }
   
    public AlmFamiliasId getId() {
        return this.id;
    }
    
    public void setId(AlmFamiliasId id) {
        this.id = id;
    }
    public String getVariante() {
        return this.variante;
    }
    
    public void setVariante(String variante) {
        this.variante = variante;
    }




}


