package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * AlmLineasxToma generated by hbm2java
 */
public class AlmLineasxToma  implements java.io.Serializable {


     private AlmLineasxTomaId id;

    public AlmLineasxToma() {
    }

    public AlmLineasxToma(AlmLineasxTomaId id) {
       this.id = id;
    }
   
    public AlmLineasxTomaId getId() {
        return this.id;
    }
    
    public void setId(AlmLineasxTomaId id) {
        this.id = id;
    }




}


