package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * AlmLineasxTomaId generated by hbm2java
 */
public class AlmLineasxTomaId  implements java.io.Serializable {


     private String codalm;
     private String codToma;
     private String codLinea;
     private String codsub;

    public AlmLineasxTomaId() {
    }

    public AlmLineasxTomaId(String codalm, String codToma, String codLinea, String codsub) {
       this.codalm = codalm;
       this.codToma = codToma;
       this.codLinea = codLinea;
       this.codsub = codsub;
    }
   
    public String getCodalm() {
        return this.codalm;
    }
    
    public void setCodalm(String codalm) {
        this.codalm = codalm;
    }
    public String getCodToma() {
        return this.codToma;
    }
    
    public void setCodToma(String codToma) {
        this.codToma = codToma;
    }
    public String getCodLinea() {
        return this.codLinea;
    }
    
    public void setCodLinea(String codLinea) {
        this.codLinea = codLinea;
    }
    public String getCodsub() {
        return this.codsub;
    }
    
    public void setCodsub(String codsub) {
        this.codsub = codsub;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlmLineasxTomaId) ) return false;
		 AlmLineasxTomaId castOther = ( AlmLineasxTomaId ) other; 
         
		 return ( (this.getCodalm()==castOther.getCodalm()) || ( this.getCodalm()!=null && castOther.getCodalm()!=null && this.getCodalm().equals(castOther.getCodalm()) ) )
 && ( (this.getCodToma()==castOther.getCodToma()) || ( this.getCodToma()!=null && castOther.getCodToma()!=null && this.getCodToma().equals(castOther.getCodToma()) ) )
 && ( (this.getCodLinea()==castOther.getCodLinea()) || ( this.getCodLinea()!=null && castOther.getCodLinea()!=null && this.getCodLinea().equals(castOther.getCodLinea()) ) )
 && ( (this.getCodsub()==castOther.getCodsub()) || ( this.getCodsub()!=null && castOther.getCodsub()!=null && this.getCodsub().equals(castOther.getCodsub()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodalm() == null ? 0 : this.getCodalm().hashCode() );
         result = 37 * result + ( getCodToma() == null ? 0 : this.getCodToma().hashCode() );
         result = 37 * result + ( getCodLinea() == null ? 0 : this.getCodLinea().hashCode() );
         result = 37 * result + ( getCodsub() == null ? 0 : this.getCodsub().hashCode() );
         return result;
   }   


}


