package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * AlmLineas generated by hbm2java
 */
public class AlmLineas  implements java.io.Serializable {


     private AlmLineasId id;
     private String nomlinea;
     private boolean modificado;
     private String codgrutdef;

    public AlmLineas() {
    }

	
    public AlmLineas(AlmLineasId id, boolean modificado, String codgrutdef) {
        this.id = id;
        this.modificado = modificado;
        this.codgrutdef = codgrutdef;
    }
    public AlmLineas(AlmLineasId id, String nomlinea, boolean modificado, String codgrutdef) {
       this.id = id;
       this.nomlinea = nomlinea;
       this.modificado = modificado;
       this.codgrutdef = codgrutdef;
    }
   
    public AlmLineasId getId() {
        return this.id;
    }
    
    public void setId(AlmLineasId id) {
        this.id = id;
    }
    public String getNomlinea() {
        return this.nomlinea;
    }
    
    public void setNomlinea(String nomlinea) {
        this.nomlinea = nomlinea;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }
    public String getCodgrutdef() {
        return this.codgrutdef;
    }
    
    public void setCodgrutdef(String codgrutdef) {
        this.codgrutdef = codgrutdef;
    }




}


