package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * AlmMaeDise�oCb generated by hbm2java
 */
public class AlmMaeDiseñoCb  implements java.io.Serializable {


     private String coddis;
     private String nomdis;

    public AlmMaeDiseñoCb() {
    }

    public AlmMaeDiseñoCb(String coddis, String nomdis) {
       this.coddis = coddis;
       this.nomdis = nomdis;
    }
   
    public String getCoddis() {
        return this.coddis;
    }
    
    public void setCoddis(String coddis) {
        this.coddis = coddis;
    }
    public String getNomdis() {
        return this.nomdis;
    }
    
    public void setNomdis(String nomdis) {
        this.nomdis = nomdis;
    }




}


