package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CfgConsecxTrans generated by hbm2java
 */
public class CfgConsecxTrans  implements java.io.Serializable {


     private String idProcess;
     private String descrip;
     private String codcon;
     private String modulo;
     private String codfue;
     private boolean contabiliza;

    public CfgConsecxTrans() {
    }

	
    public CfgConsecxTrans(String idProcess, String codcon, String modulo, String codfue, boolean contabiliza) {
        this.idProcess = idProcess;
        this.codcon = codcon;
        this.modulo = modulo;
        this.codfue = codfue;
        this.contabiliza = contabiliza;
    }
    public CfgConsecxTrans(String idProcess, String descrip, String codcon, String modulo, String codfue, boolean contabiliza) {
       this.idProcess = idProcess;
       this.descrip = descrip;
       this.codcon = codcon;
       this.modulo = modulo;
       this.codfue = codfue;
       this.contabiliza = contabiliza;
    }
   
    public String getIdProcess() {
        return this.idProcess;
    }
    
    public void setIdProcess(String idProcess) {
        this.idProcess = idProcess;
    }
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }
    public String getCodcon() {
        return this.codcon;
    }
    
    public void setCodcon(String codcon) {
        this.codcon = codcon;
    }
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }
    public String getCodfue() {
        return this.codfue;
    }
    
    public void setCodfue(String codfue) {
        this.codfue = codfue;
    }
    public boolean isContabiliza() {
        return this.contabiliza;
    }
    
    public void setContabiliza(boolean contabiliza) {
        this.contabiliza = contabiliza;
    }




}


