package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CfgDetaPerfil generated by hbm2java
 */
public class CfgDetaPerfil  implements java.io.Serializable {


     private CfgDetaPerfilId id;

    public CfgDetaPerfil() {
    }

    public CfgDetaPerfil(CfgDetaPerfilId id) {
       this.id = id;
    }
   
    public CfgDetaPerfilId getId() {
        return this.id;
    }
    
    public void setId(CfgDetaPerfilId id) {
        this.id = id;
    }




}


