package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CfgPerfilxUsua generated by hbm2java
 */
public class CfgPerfilxUsua  implements java.io.Serializable {


     private CfgPerfilxUsuaId id;

    public CfgPerfilxUsua() {
    }

    public CfgPerfilxUsua(CfgPerfilxUsuaId id) {
       this.id = id;
    }
   
    public CfgPerfilxUsuaId getId() {
        return this.id;
    }
    
    public void setId(CfgPerfilxUsuaId id) {
        this.id = id;
    }




}


