package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CfgUsuariosxAlm generated by hbm2java
 */
public class CfgUsuariosxAlm  implements java.io.Serializable {


     private CfgUsuariosxAlmId id;

    public CfgUsuariosxAlm() {
    }

    public CfgUsuariosxAlm(CfgUsuariosxAlmId id) {
       this.id = id;
    }
   
    public CfgUsuariosxAlmId getId() {
        return this.id;
    }
    
    public void setId(CfgUsuariosxAlmId id) {
        this.id = id;
    }




}


