package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntCenCostos generated by hbm2java
 */
public class CntCenCostos  implements java.io.Serializable {


     private String codCen;
     private String nomCen;
     private boolean modificado;
     private String codCosPadre;

    public CntCenCostos() {
    }

    public CntCenCostos(String codCen, String nomCen, boolean modificado, String codCosPadre) {
       this.codCen = codCen;
       this.nomCen = nomCen;
       this.modificado = modificado;
       this.codCosPadre = codCosPadre;
    }
   
    public String getCodCen() {
        return this.codCen;
    }
    
    public void setCodCen(String codCen) {
        this.codCen = codCen;
    }
    public String getNomCen() {
        return this.nomCen;
    }
    
    public void setNomCen(String nomCen) {
        this.nomCen = nomCen;
    }
    public boolean isModificado() {
        return this.modificado;
    }
    
    public void setModificado(boolean modificado) {
        this.modificado = modificado;
    }
    public String getCodCosPadre() {
        return this.codCosPadre;
    }
    
    public void setCodCosPadre(String codCosPadre) {
        this.codCosPadre = codCosPadre;
    }




}


