package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntFiltros generated by hbm2java
 */
public class CntFiltros  implements java.io.Serializable {


     private String idProcess;
     private String filtro;

    public CntFiltros() {
    }

    public CntFiltros(String idProcess, String filtro) {
       this.idProcess = idProcess;
       this.filtro = filtro;
    }
   
    public String getIdProcess() {
        return this.idProcess;
    }
    
    public void setIdProcess(String idProcess) {
        this.idProcess = idProcess;
    }
    public String getFiltro() {
        return this.filtro;
    }
    
    public void setFiltro(String filtro) {
        this.filtro = filtro;
    }




}


