package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntInvParVentas generated by hbm2java
 */
public class CntInvParVentas  implements java.io.Serializable {


     private CntInvParVentasId id;
     private String ctaIngresos;
     private String ctaIvaGenerado;
     private String ctaCostoVta;
     private String ctaInventario;
     private String ctaAdmAiu;
     private String ctaImpAiu;
     private String ctaUtlAiu;

    public CntInvParVentas() {
    }

    public CntInvParVentas(CntInvParVentasId id, String ctaIngresos, String ctaIvaGenerado, String ctaCostoVta, String ctaInventario, String ctaAdmAiu, String ctaImpAiu, String ctaUtlAiu) {
       this.id = id;
       this.ctaIngresos = ctaIngresos;
       this.ctaIvaGenerado = ctaIvaGenerado;
       this.ctaCostoVta = ctaCostoVta;
       this.ctaInventario = ctaInventario;
       this.ctaAdmAiu = ctaAdmAiu;
       this.ctaImpAiu = ctaImpAiu;
       this.ctaUtlAiu = ctaUtlAiu;
    }
   
    public CntInvParVentasId getId() {
        return this.id;
    }
    
    public void setId(CntInvParVentasId id) {
        this.id = id;
    }
    public String getCtaIngresos() {
        return this.ctaIngresos;
    }
    
    public void setCtaIngresos(String ctaIngresos) {
        this.ctaIngresos = ctaIngresos;
    }
    public String getCtaIvaGenerado() {
        return this.ctaIvaGenerado;
    }
    
    public void setCtaIvaGenerado(String ctaIvaGenerado) {
        this.ctaIvaGenerado = ctaIvaGenerado;
    }
    public String getCtaCostoVta() {
        return this.ctaCostoVta;
    }
    
    public void setCtaCostoVta(String ctaCostoVta) {
        this.ctaCostoVta = ctaCostoVta;
    }
    public String getCtaInventario() {
        return this.ctaInventario;
    }
    
    public void setCtaInventario(String ctaInventario) {
        this.ctaInventario = ctaInventario;
    }
    public String getCtaAdmAiu() {
        return this.ctaAdmAiu;
    }
    
    public void setCtaAdmAiu(String ctaAdmAiu) {
        this.ctaAdmAiu = ctaAdmAiu;
    }
    public String getCtaImpAiu() {
        return this.ctaImpAiu;
    }
    
    public void setCtaImpAiu(String ctaImpAiu) {
        this.ctaImpAiu = ctaImpAiu;
    }
    public String getCtaUtlAiu() {
        return this.ctaUtlAiu;
    }
    
    public void setCtaUtlAiu(String ctaUtlAiu) {
        this.ctaUtlAiu = ctaUtlAiu;
    }




}


