package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntInvParCompras generated by hbm2java
 */
public class CntInvParCompras  implements java.io.Serializable {


     private CntInvParComprasId id;
     private String ctaIvaDescontable;
     private String ctaAdivaDescontable;

    public CntInvParCompras() {
    }

    public CntInvParCompras(CntInvParComprasId id, String ctaIvaDescontable, String ctaAdivaDescontable) {
       this.id = id;
       this.ctaIvaDescontable = ctaIvaDescontable;
       this.ctaAdivaDescontable = ctaAdivaDescontable;
    }
   
    public CntInvParComprasId getId() {
        return this.id;
    }
    
    public void setId(CntInvParComprasId id) {
        this.id = id;
    }
    public String getCtaIvaDescontable() {
        return this.ctaIvaDescontable;
    }
    
    public void setCtaIvaDescontable(String ctaIvaDescontable) {
        this.ctaIvaDescontable = ctaIvaDescontable;
    }
    public String getCtaAdivaDescontable() {
        return this.ctaAdivaDescontable;
    }
    
    public void setCtaAdivaDescontable(String ctaAdivaDescontable) {
        this.ctaAdivaDescontable = ctaAdivaDescontable;
    }




}


