package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntMmdetaConceptos generated by hbm2java
 */
public class CntMmdetaConceptos  implements java.io.Serializable {


     private CntMmdetaConceptosId id;
     private char natSum;

    public CntMmdetaConceptos() {
    }

    public CntMmdetaConceptos(CntMmdetaConceptosId id, char natSum) {
       this.id = id;
       this.natSum = natSum;
    }
   
    public CntMmdetaConceptosId getId() {
        return this.id;
    }
    
    public void setId(CntMmdetaConceptosId id) {
        this.id = id;
    }
    public char getNatSum() {
        return this.natSum;
    }
    
    public void setNatSum(char natSum) {
        this.natSum = natSum;
    }




}


