package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntMmmaeConceptos generated by hbm2java
 */
public class CntMmmaeConceptos  implements java.io.Serializable {


     private CntMmmaeConceptosId id;
     private String nomCon;
     private String forCodFue;

    public CntMmmaeConceptos() {
    }

    public CntMmmaeConceptos(CntMmmaeConceptosId id, String nomCon, String forCodFue) {
       this.id = id;
       this.nomCon = nomCon;
       this.forCodFue = forCodFue;
    }
   
    public CntMmmaeConceptosId getId() {
        return this.id;
    }
    
    public void setId(CntMmmaeConceptosId id) {
        this.id = id;
    }
    public String getNomCon() {
        return this.nomCon;
    }
    
    public void setNomCon(String nomCon) {
        this.nomCon = nomCon;
    }
    public String getForCodFue() {
        return this.forCodFue;
    }
    
    public void setForCodFue(String forCodFue) {
        this.forCodFue = forCodFue;
    }




}


