package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntMmformatos generated by hbm2java
 */
public class CntMmformatos  implements java.io.Serializable {


     private String codFor;
     private String nomFor;

    public CntMmformatos() {
    }

    public CntMmformatos(String codFor, String nomFor) {
       this.codFor = codFor;
       this.nomFor = nomFor;
    }
   
    public String getCodFor() {
        return this.codFor;
    }
    
    public void setCodFor(String codFor) {
        this.codFor = codFor;
    }
    public String getNomFor() {
        return this.nomFor;
    }
    
    public void setNomFor(String nomFor) {
        this.nomFor = nomFor;
    }




}


