package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CntPeriodos generated by hbm2java
 */
public class CntPeriodos  implements java.io.Serializable {


     private CntPeriodosId id;
     private String estado;

    public CntPeriodos() {
    }

    public CntPeriodos(CntPeriodosId id, String estado) {
       this.id = id;
       this.estado = estado;
    }
   
    public CntPeriodosId getId() {
        return this.id;
    }
    
    public void setId(CntPeriodosId id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


