package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CxPObservaCom generated by hbm2java
 */
public class CxPObservaCom  implements java.io.Serializable {


     private CxPObservaComId id;
     private String observa;

    public CxPObservaCom() {
    }

    public CxPObservaCom(CxPObservaComId id, String observa) {
       this.id = id;
       this.observa = observa;
    }
   
    public CxPObservaComId getId() {
        return this.id;
    }
    
    public void setId(CxPObservaComId id) {
        this.id = id;
    }
    public String getObserva() {
        return this.observa;
    }
    
    public void setObserva(String observa) {
        this.observa = observa;
    }




}


