package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CxPRetIcaxFac generated by hbm2java
 */
public class CxPRetIcaxFac  implements java.io.Serializable {


     private CxPRetIcaxFacId id;
     private BigDecimal base;
     private BigDecimal valRet;
     private BigDecimal margen;
     private boolean baseModif;

    public CxPRetIcaxFac() {
    }

    public CxPRetIcaxFac(CxPRetIcaxFacId id, BigDecimal base, BigDecimal valRet, BigDecimal margen, boolean baseModif) {
       this.id = id;
       this.base = base;
       this.valRet = valRet;
       this.margen = margen;
       this.baseModif = baseModif;
    }
   
    public CxPRetIcaxFacId getId() {
        return this.id;
    }
    
    public void setId(CxPRetIcaxFacId id) {
        this.id = id;
    }
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }
    public BigDecimal getValRet() {
        return this.valRet;
    }
    
    public void setValRet(BigDecimal valRet) {
        this.valRet = valRet;
    }
    public BigDecimal getMargen() {
        return this.margen;
    }
    
    public void setMargen(BigDecimal margen) {
        this.margen = margen;
    }
    public boolean isBaseModif() {
        return this.baseModif;
    }
    
    public void setBaseModif(boolean baseModif) {
        this.baseModif = baseModif;
    }




}


