package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * CxPRetsXProv generated by hbm2java
 */
public class CxPRetsXProv  implements java.io.Serializable {


     private CxPRetsXProvId id;

    public CxPRetsXProv() {
    }

    public CxPRetsXProv(CxPRetsXProvId id) {
       this.id = id;
    }
   
    public CxPRetsXProvId getId() {
        return this.id;
    }
    
    public void setId(CxPRetsXProvId id) {
        this.id = id;
    }




}


