package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CxPRetxFac generated by hbm2java
 */
public class CxPRetxFac  implements java.io.Serializable {


     private CxPRetxFacId id;
     private BigDecimal base;
     private BigDecimal valRet;
     private String regPropiet;
     private BigDecimal margen;
     private boolean baseModif;

    public CxPRetxFac() {
    }

    public CxPRetxFac(CxPRetxFacId id, BigDecimal base, BigDecimal valRet, String regPropiet, BigDecimal margen, boolean baseModif) {
       this.id = id;
       this.base = base;
       this.valRet = valRet;
       this.regPropiet = regPropiet;
       this.margen = margen;
       this.baseModif = baseModif;
    }
   
    public CxPRetxFacId getId() {
        return this.id;
    }
    
    public void setId(CxPRetxFacId id) {
        this.id = id;
    }
    public BigDecimal getBase() {
        return this.base;
    }
    
    public void setBase(BigDecimal base) {
        this.base = base;
    }
    public BigDecimal getValRet() {
        return this.valRet;
    }
    
    public void setValRet(BigDecimal valRet) {
        this.valRet = valRet;
    }
    public String getRegPropiet() {
        return this.regPropiet;
    }
    
    public void setRegPropiet(String regPropiet) {
        this.regPropiet = regPropiet;
    }
    public BigDecimal getMargen() {
        return this.margen;
    }
    
    public void setMargen(BigDecimal margen) {
        this.margen = margen;
    }
    public boolean isBaseModif() {
        return this.baseModif;
    }
    
    public void setBaseModif(boolean baseModif) {
        this.baseModif = baseModif;
    }




}


