package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * FelDevolucionesId generated by hbm2java
 */
public class FelDevolucionesId  implements java.io.Serializable {


     private String codAlm;
     private String numFac;
     private String tipFac;
     private String codRes;
     private String codIns;
     private String idreg;

    public FelDevolucionesId() {
    }

    public FelDevolucionesId(String codAlm, String numFac, String tipFac, String codRes, String codIns, String idreg) {
       this.codAlm = codAlm;
       this.numFac = numFac;
       this.tipFac = tipFac;
       this.codRes = codRes;
       this.codIns = codIns;
       this.idreg = idreg;
    }
   
    public String getCodAlm() {
        return this.codAlm;
    }
    
    public void setCodAlm(String codAlm) {
        this.codAlm = codAlm;
    }
    public String getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(String numFac) {
        this.numFac = numFac;
    }
    public String getTipFac() {
        return this.tipFac;
    }
    
    public void setTipFac(String tipFac) {
        this.tipFac = tipFac;
    }
    public String getCodRes() {
        return this.codRes;
    }
    
    public void setCodRes(String codRes) {
        this.codRes = codRes;
    }
    public String getCodIns() {
        return this.codIns;
    }
    
    public void setCodIns(String codIns) {
        this.codIns = codIns;
    }
    public String getIdreg() {
        return this.idreg;
    }
    
    public void setIdreg(String idreg) {
        this.idreg = idreg;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FelDevolucionesId) ) return false;
		 FelDevolucionesId castOther = ( FelDevolucionesId ) other; 
         
		 return ( (this.getCodAlm()==castOther.getCodAlm()) || ( this.getCodAlm()!=null && castOther.getCodAlm()!=null && this.getCodAlm().equals(castOther.getCodAlm()) ) )
 && ( (this.getNumFac()==castOther.getNumFac()) || ( this.getNumFac()!=null && castOther.getNumFac()!=null && this.getNumFac().equals(castOther.getNumFac()) ) )
 && ( (this.getTipFac()==castOther.getTipFac()) || ( this.getTipFac()!=null && castOther.getTipFac()!=null && this.getTipFac().equals(castOther.getTipFac()) ) )
 && ( (this.getCodRes()==castOther.getCodRes()) || ( this.getCodRes()!=null && castOther.getCodRes()!=null && this.getCodRes().equals(castOther.getCodRes()) ) )
 && ( (this.getCodIns()==castOther.getCodIns()) || ( this.getCodIns()!=null && castOther.getCodIns()!=null && this.getCodIns().equals(castOther.getCodIns()) ) )
 && ( (this.getIdreg()==castOther.getIdreg()) || ( this.getIdreg()!=null && castOther.getIdreg()!=null && this.getIdreg().equals(castOther.getIdreg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAlm() == null ? 0 : this.getCodAlm().hashCode() );
         result = 37 * result + ( getNumFac() == null ? 0 : this.getNumFac().hashCode() );
         result = 37 * result + ( getTipFac() == null ? 0 : this.getTipFac().hashCode() );
         result = 37 * result + ( getCodRes() == null ? 0 : this.getCodRes().hashCode() );
         result = 37 * result + ( getCodIns() == null ? 0 : this.getCodIns().hashCode() );
         result = 37 * result + ( getIdreg() == null ? 0 : this.getIdreg().hashCode() );
         return result;
   }   


}


