package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * FelDistribucion generated by hbm2java
 */
public class FelDistribucion  implements java.io.Serializable {


     private FelDistribucionId id;
     private int distribuidorId;

    public FelDistribucion() {
    }

    public FelDistribucion(FelDistribucionId id, int distribuidorId) {
       this.id = id;
       this.distribuidorId = distribuidorId;
    }
   
    public FelDistribucionId getId() {
        return this.id;
    }
    
    public void setId(FelDistribucionId id) {
        this.id = id;
    }
    public int getDistribuidorId() {
        return this.distribuidorId;
    }
    
    public void setDistribuidorId(int distribuidorId) {
        this.distribuidorId = distribuidorId;
    }




}


