package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * GenConsecS generated by hbm2java
 */
public class GenConsecS  implements java.io.Serializable {


     private GenConsecSId id;
     private Integer consecutivo;

    public GenConsecS() {
    }

	
    public GenConsecS(GenConsecSId id) {
        this.id = id;
    }
    public GenConsecS(GenConsecSId id, Integer consecutivo) {
       this.id = id;
       this.consecutivo = consecutivo;
    }
   
    public GenConsecSId getId() {
        return this.id;
    }
    
    public void setId(GenConsecSId id) {
        this.id = id;
    }
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }




}


