package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * GenFavoritos generated by hbm2java
 */
public class GenFavoritos  implements java.io.Serializable {


     private GenFavoritosId id;

    public GenFavoritos() {
    }

    public GenFavoritos(GenFavoritosId id) {
       this.id = id;
    }
   
    public GenFavoritosId getId() {
        return this.id;
    }
    
    public void setId(GenFavoritosId id) {
        this.id = id;
    }




}


