package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * GenMonedas generated by hbm2java
 */
public class GenMonedas  implements java.io.Serializable {


     private String codmon;
     private String nommon;
     private String abrevia;

    public GenMonedas() {
    }

    public GenMonedas(String codmon, String nommon, String abrevia) {
       this.codmon = codmon;
       this.nommon = nommon;
       this.abrevia = abrevia;
    }
   
    public String getCodmon() {
        return this.codmon;
    }
    
    public void setCodmon(String codmon) {
        this.codmon = codmon;
    }
    public String getNommon() {
        return this.nommon;
    }
    
    public void setNommon(String nommon) {
        this.nommon = nommon;
    }
    public String getAbrevia() {
        return this.abrevia;
    }
    
    public void setAbrevia(String abrevia) {
        this.abrevia = abrevia;
    }




}


