package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * GenNotificaIds generated by hbm2java
 */
public class GenNotificaIds  implements java.io.Serializable {


     private String idProcess;
     private String descrip;

    public GenNotificaIds() {
    }

    public GenNotificaIds(String idProcess, String descrip) {
       this.idProcess = idProcess;
       this.descrip = descrip;
    }
   
    public String getIdProcess() {
        return this.idProcess;
    }
    
    public void setIdProcess(String idProcess) {
        this.idProcess = idProcess;
    }
    public String getDescrip() {
        return this.descrip;
    }
    
    public void setDescrip(String descrip) {
        this.descrip = descrip;
    }




}


