package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * GenNotificaEventos generated by hbm2java
 */
public class GenNotificaEventos  implements java.io.Serializable {


     private GenNotificaEventosId id;

    public GenNotificaEventos() {
    }

    public GenNotificaEventos(GenNotificaEventosId id) {
       this.id = id;
    }
   
    public GenNotificaEventosId getId() {
        return this.id;
    }
    
    public void setId(GenNotificaEventosId id) {
        this.id = id;
    }




}


