package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * GenTrazaDocFromDoc generated by hbm2java
 */
public class GenTrazaDocFromDoc  implements java.io.Serializable {


     private GenTrazaDocFromDocId id;
     private String numDocNew;

    public GenTrazaDocFromDoc() {
    }

    public GenTrazaDocFromDoc(GenTrazaDocFromDocId id, String numDocNew) {
       this.id = id;
       this.numDocNew = numDocNew;
    }
   
    public GenTrazaDocFromDocId getId() {
        return this.id;
    }
    
    public void setId(GenTrazaDocFromDocId id) {
        this.id = id;
    }
    public String getNumDocNew() {
        return this.numDocNew;
    }
    
    public void setNumDocNew(String numDocNew) {
        this.numDocNew = numDocNew;
    }




}


