package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * MlDetaTalonario generated by hbm2java
 */
public class MlDetaTalonario  implements java.io.Serializable {


     private MlDetaTalonarioId id;
     private String codVen;
     private String numRecS;
     private String codAlmS;
     private String tipRecS;
     private String estado;
     private String observa;

    public MlDetaTalonario() {
    }

    public MlDetaTalonario(MlDetaTalonarioId id, String codVen, String numRecS, String codAlmS, String tipRecS, String estado, String observa) {
       this.id = id;
       this.codVen = codVen;
       this.numRecS = numRecS;
       this.codAlmS = codAlmS;
       this.tipRecS = tipRecS;
       this.estado = estado;
       this.observa = observa;
    }
   
    public MlDetaTalonarioId getId() {
        return this.id;
    }
    
    public void setId(MlDetaTalonarioId id) {
        this.id = id;
    }
    public String getCodVen() {
        return this.codVen;
    }
    
    public void setCodVen(String codVen) {
        this.codVen = codVen;
    }
    public String getNumRecS() {
        return this.numRecS;
    }
    
    public void setNumRecS(String numRecS) {
        this.numRecS = numRecS;
    }
    public String getCodAlmS() {
        return this.codAlmS;
    }
    
    public void setCodAlmS(String codAlmS) {
        this.codAlmS = codAlmS;
    }
    public String getTipRecS() {
        return this.tipRecS;
    }
    
    public void setTipRecS(String tipRecS) {
        this.tipRecS = tipRecS;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObserva() {
        return this.observa;
    }
    
    public void setObserva(String observa) {
        this.observa = observa;
    }




}


