package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * MlProducto generated by hbm2java
 */
public class MlProducto  implements java.io.Serializable {


     private String codProd;
     private String nomProd;

    public MlProducto() {
    }

    public MlProducto(String codProd, String nomProd) {
       this.codProd = codProd;
       this.nomProd = nomProd;
    }
   
    public String getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }
    public String getNomProd() {
        return this.nomProd;
    }
    
    public void setNomProd(String nomProd) {
        this.nomProd = nomProd;
    }




}


