package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * MlTipo generated by hbm2java
 */
public class MlTipo  implements java.io.Serializable {


     private String codTipo;
     private String nomTipo;

    public MlTipo() {
    }

    public MlTipo(String codTipo, String nomTipo) {
       this.codTipo = codTipo;
       this.nomTipo = nomTipo;
    }
   
    public String getCodTipo() {
        return this.codTipo;
    }
    
    public void setCodTipo(String codTipo) {
        this.codTipo = codTipo;
    }
    public String getNomTipo() {
        return this.nomTipo;
    }
    
    public void setNomTipo(String nomTipo) {
        this.nomTipo = nomTipo;
    }




}


