package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * NomCargos generated by hbm2java
 */
public class NomCargos  implements java.io.Serializable {


     private String codCargo;
     private String nomCargo;

    public NomCargos() {
    }

    public NomCargos(String codCargo, String nomCargo) {
       this.codCargo = codCargo;
       this.nomCargo = nomCargo;
    }
   
    public String getCodCargo() {
        return this.codCargo;
    }
    
    public void setCodCargo(String codCargo) {
        this.codCargo = codCargo;
    }
    public String getNomCargo() {
        return this.nomCargo;
    }
    
    public void setNomCargo(String nomCargo) {
        this.nomCargo = nomCargo;
    }




}


