package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * NomLiqsTrans generated by hbm2java
 */
public class NomLiqsTrans  implements java.io.Serializable {


     private NomLiqsTransId id;

    public NomLiqsTrans() {
    }

    public NomLiqsTrans(NomLiqsTransId id) {
       this.id = id;
    }
   
    public NomLiqsTransId getId() {
        return this.id;
    }
    
    public void setId(NomLiqsTransId id) {
        this.id = id;
    }




}


