package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * NomPeriodosxVar generated by hbm2java
 */
public class NomPeriodosxVar  implements java.io.Serializable {


     private NomPeriodosxVarId id;

    public NomPeriodosxVar() {
    }

    public NomPeriodosxVar(NomPeriodosxVarId id) {
       this.id = id;
    }
   
    public NomPeriodosxVarId getId() {
        return this.id;
    }
    
    public void setId(NomPeriodosxVarId id) {
        this.id = id;
    }




}


