package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * NomSecciones generated by hbm2java
 */
public class NomSecciones  implements java.io.Serializable {


     private String codSec;
     private String nomSec;
     private int periodoLiq;

    public NomSecciones() {
    }

    public NomSecciones(String codSec, String nomSec, int periodoLiq) {
       this.codSec = codSec;
       this.nomSec = nomSec;
       this.periodoLiq = periodoLiq;
    }
   
    public String getCodSec() {
        return this.codSec;
    }
    
    public void setCodSec(String codSec) {
        this.codSec = codSec;
    }
    public String getNomSec() {
        return this.nomSec;
    }
    
    public void setNomSec(String nomSec) {
        this.nomSec = nomSec;
    }
    public int getPeriodoLiq() {
        return this.periodoLiq;
    }
    
    public void setPeriodoLiq(int periodoLiq) {
        this.periodoLiq = periodoLiq;
    }




}


