package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * NomTersxTran generated by hbm2java
 */
public class NomTersxTran  implements java.io.Serializable {


     private NomTersxTranId id;
     private String idter;

    public NomTersxTran() {
    }

    public NomTersxTran(NomTersxTranId id, String idter) {
       this.id = id;
       this.idter = idter;
    }
   
    public NomTersxTranId getId() {
        return this.id;
    }
    
    public void setId(NomTersxTranId id) {
        this.id = id;
    }
    public String getIdter() {
        return this.idter;
    }
    
    public void setIdter(String idter) {
        this.idter = idter;
    }




}


