package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * NomTransxVar generated by hbm2java
 */
public class NomTransxVar  implements java.io.Serializable {


     private NomTransxVarId id;

    public NomTransxVar() {
    }

    public NomTransxVar(NomTransxVarId id) {
       this.id = id;
    }
   
    public NomTransxVarId getId() {
        return this.id;
    }
    
    public void setId(NomTransxVarId id) {
        this.id = id;
    }




}


