package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * NomUndTrans generated by hbm2java
 */
public class NomUndTrans  implements java.io.Serializable {


     private String codUni;
     private String nomUni;
     private boolean sistema;

    public NomUndTrans() {
    }

    public NomUndTrans(String codUni, String nomUni, boolean sistema) {
       this.codUni = codUni;
       this.nomUni = nomUni;
       this.sistema = sistema;
    }
   
    public String getCodUni() {
        return this.codUni;
    }
    
    public void setCodUni(String codUni) {
        this.codUni = codUni;
    }
    public String getNomUni() {
        return this.nomUni;
    }
    
    public void setNomUni(String nomUni) {
        this.nomUni = nomUni;
    }
    public boolean isSistema() {
        return this.sistema;
    }
    
    public void setSistema(boolean sistema) {
        this.sistema = sistema;
    }




}


