package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * TesCtasBancariasxAlm generated by hbm2java
 */
public class TesCtasBancariasxAlm  implements java.io.Serializable {


     private TesCtasBancariasxAlmId id;

    public TesCtasBancariasxAlm() {
    }

    public TesCtasBancariasxAlm(TesCtasBancariasxAlmId id) {
       this.id = id;
    }
   
    public TesCtasBancariasxAlmId getId() {
        return this.id;
    }
    
    public void setId(TesCtasBancariasxAlmId id) {
        this.id = id;
    }




}


