package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * TesCajasxUsu generated by hbm2java
 */
public class TesCajasxUsu  implements java.io.Serializable {


     private TesCajasxUsuId id;

    public TesCajasxUsu() {
    }

    public TesCajasxUsu(TesCajasxUsuId id) {
       this.id = id;
    }
   
    public TesCajasxUsuId getId() {
        return this.id;
    }
    
    public void setId(TesCajasxUsuId id) {
        this.id = id;
    }




}


