package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * TesCtasBancariasxUsu generated by hbm2java
 */
public class TesCtasBancariasxUsu  implements java.io.Serializable {


     private TesCtasBancariasxUsuId id;

    public TesCtasBancariasxUsu() {
    }

    public TesCtasBancariasxUsu(TesCtasBancariasxUsuId id) {
       this.id = id;
    }
   
    public TesCtasBancariasxUsuId getId() {
        return this.id;
    }
    
    public void setId(TesCtasBancariasxUsuId id) {
        this.id = id;
    }




}


