package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VenCupos generated by hbm2java
 */
public class VenCupos  implements java.io.Serializable {


     private String cedula;
     private BigDecimal autorizado;

    public VenCupos() {
    }

    public VenCupos(String cedula, BigDecimal autorizado) {
       this.cedula = cedula;
       this.autorizado = autorizado;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public BigDecimal getAutorizado() {
        return this.autorizado;
    }
    
    public void setAutorizado(BigDecimal autorizado) {
        this.autorizado = autorizado;
    }




}


