package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * VenFpsxLp generated by hbm2java
 */
public class VenFpsxLp  implements java.io.Serializable {


     private VenFpsxLpId id;

    public VenFpsxLp() {
    }

    public VenFpsxLp(VenFpsxLpId id) {
       this.id = id;
    }
   
    public VenFpsxLpId getId() {
        return this.id;
    }
    
    public void setId(VenFpsxLpId id) {
        this.id = id;
    }




}


