package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * VenRetsXCliente generated by hbm2java
 */
public class VenRetsXCliente  implements java.io.Serializable {


     private VenRetsXClienteId id;

    public VenRetsXCliente() {
    }

    public VenRetsXCliente(VenRetsXClienteId id) {
       this.id = id;
    }
   
    public VenRetsXClienteId getId() {
        return this.id;
    }
    
    public void setId(VenRetsXClienteId id) {
        this.id = id;
    }




}


