package POJOS;
// Generated 5/12/2014 10:43:46 AM by Hibernate Tools 4.3.1



/**
 * VenVendxAlm generated by hbm2java
 */
public class VenVendxAlm  implements java.io.Serializable {


     private VenVendxAlmId id;

    public VenVendxAlm() {
    }

    public VenVendxAlm(VenVendxAlmId id) {
       this.id = id;
    }
   
    public VenVendxAlmId getId() {
        return this.id;
    }
    
    public void setId(VenVendxAlmId id) {
        this.id = id;
    }




}


